package com.it.ocs.itemDescribe.css;

import com.it.ocs.itemDescribe.Base.BaseCss;

public class TemplateACss extends BaseCss {
	
	public static String css="*{"+"\n"
			+"	margin: 0;"+"\n"
			+"	padding: 0;"+"\n"
			+"}"+"\n"
			+"html,body{"+"\n"
			+"	font-size: 14px;"+"\n"
			+"}"+"\n"
			+"li {"+"\n"
			+"	list-style: none;"+"\n"
			+"}"+"\n"
			+"a {"+"\n"
			+"	text-decoration: none;"+"\n"
			+"	color:#000000;"+"\n"
			+"	"+"\n"
			+"}"+"\n"
			+"body{"+"\n"
//			+"	min-width: 1900px;"+"\n"
			+"	font-family: 'Lato', 'Arial'; 	"+"\n"
			+"}"+"\n"
			+" /* * */.section_background{"+"\n"
			+"	width:100%;"+"\n"
			+"	background:	url(https://timage.pushauction.com/v3/DefaultTemplate/A16285/bg.jpg);"+"\n"
			+"	padding-top:20px;"+"\n"
			+"}"+"\n"
			+".left{"+"\n"
			+"	float:left;"+"\n"
			+"}"+"\n"
			+".right{"+"\n"
			+"	float: right;"+"\n"
			+"}"+"\n"
			+".after:after{"+"\n"
			+"	content:\"\";"+"\n"
			+"	display: block;"+"\n"
			+"	clear:both;"+"\n"
			+"}"+"\n"
			+" /*增加 */header{padding-bottom:10px;}"+"\n"
			+".header-pro,.footer_pro{"+"\n"
			+"	margin:5px;"+"\n"
			+"	margin-bottom:0;"+"\n"
			+"	border-bottom:1px solid grey;"+"\n"
			+"	height:445px;"+"\n"
			+"}"+"\n"
			+".pro{"+"\n"
			+"	width:15.5%;"+"\n"
			+"	height:420px;"+"\n"
			+"	padding: 5px;"+"\n"
			+"	font-size:12px;"+"\n"
			+"	border:1px solid white;"+"\n"
			+"	cursor: pointer;"+"\n"
			+"	position:relative;"+"\n"
			+"  over-flow:hidden"+"\n"
			+ "}"+"\n"
			+".pro a:hover{text-decoration: underline #000000;}"+"\n"
			+".pro:hover{"+"\n"
			+"	border:1px solid grey;"+"\n"
			+"}"+"\n"
			+".pro img{"+"\n"
			+ "width:96%;"+"\n"
			+"	margin:5px;"+"\n"
			+" max-height:216px;"+"\n"
			+ "}"+"\n"
			+"/* * */.pro:hover .mask{"+"\n"
			+"	margin:5px;"+"\n"
			+"	width:100%;"+"\n"
			+"	height:310px;"+"\n"
			+"	background:#ffffff;"+"\n"
			+"	opacity: 0.3;"+"\n"
			+"	z-index: 100;"+"\n"
			+"	position:absolute;"+"\n"
			+"	top:0;"+"\n"
			+"	left:0;"+"\n"
			+"}"+"\n"
			+".pro-info{"+"\n"
			+"	margin-top:6px;"+"\n"
			+"	margin-bottom:16px;"+"\n"
			+"}"+"\n"
			+".price,.buynow,.Freeshipping{"+"\n"
			+"	line-height:16px;"+"\n"
			+"}"+"\n"
			+" /* * */.banner{"+"\n"
			+"	top:10px;"+"\n"
			+"	height:286px;"+"\n"
			+"	background:url(https://timage.pushauction.com/v3/DefaultTemplate/A16285/store_topbg.jpg) no-repeat;"+"\n"
			+"}"+"\n"
			+".banner_area,.section_area {"+"\n"
			+"	width:1100px;"+"\n"
			+"	margin:0 auto;"+"\n"
			+"}"+"\n"
			+".banner_area{"+"\n"
			+"	position:relative;"+"\n"
			+"}"+"\n"
			+".banner_nav{"+"\n"
			+"	width:600px;"+"\n"
			+"	height:296px;"+"\n"
			+"	border-top:1px solid #b8a982;"+"\n"
			+"	line-height:54px;"+"\n"
			+"	cursor: pointer;"+"\n"
			+"}"+"\n"
			+".banner_nav li{	"+"\n"
			+"	width:68px;"+"\n"
			+"	height:54px;"+"\n"
			+"	line-height:54px;"+"\n"
			+"	text-align: center;			"+"\n"
			+"}"+"\n"
			+".banner_nav a{	"+"\n"
			+"	color:#565656;"+"\n"
			+"}"+"\n"
			+".banner_nav li:hover{"+"\n"
			+"	background:#918e9b;"+"\n"
			+"	color:#ffffff;"+"\n"
			+"}"+"\n"
			+"/***/.banner_mes{"+"\n"
			+"	position:absolute;"+"\n"
			+"	top:0;"+"\n"
			+"	right:0;"+"\n"
			+"}"+"\n"
			+"/***/.logo{"+"\n"
			+"	position:absolute;"+"\n"
			+"	top:95px;"+"\n"
			+"	left:0px;"+"\n"
			+"}"+"\n"
			+" /*删除*/"+"\n"
			+"/*.banner_mes img{vertical-align: middle;} */"+"\n"
			+"/*删除*/"+"\n"
			+"/*.banner_mes_line{"+"\n"
			+"	height:25px;"+"\n"
			+"	width:1px;"+"\n"
			+"	background:#6b6b6b;"+"\n"
			+"	margin:0 20px;"+"\n"
			+"}*/"+"\n"
			+"aside{"+"\n"
			+"	width:220px;"+"\n"
			+"}"+"\n"
			+".store_category_nav{"+"\n"
			+"	padding-bottom:20px;"+"\n"
			+"}"+"\n"
			+".store_category_nav,.also_like_nav{"+"\n"
			+"	width:220px;"+"\n"
			+"	border:1px solid #999999;"+"\n"
			+"	background:#ffffff;"+"\n"
			+"}"+"\n"
			+"/* * */.store_category_nav li{"+"\n"
			+"	padding:10px 0;"+"\n"
			+"	line-height:14px;	"+"\n"
			+"}"+"\n"
			+".store_category_nav a{color:#000000;}"+"\n"
			+"/* * */.store_category_nav_icon{"+"\n"
			+"	float: left;"+"\n"
			+"    margin: 7px 10px;"+"\n"
			+"    width: 0;"+"\n"
			+"    height: 0;"+"\n"
			+"    border-top: 5px solid transparent;"+"\n"
			+"    border-left: 5px solid #ccc;"+"\n"
			+"    border-bottom: 5px solid transparent;"+"\n"
			+"    font-size: 0;"+"\n"
			+"}"+"\n"
			+"/* * */.store_category_nav li:hover div{"+"\n"
			+"	    border-left: 5px solid #000000;"+"\n"
			+"}"+"\n"
			+".store_category_nav li:hover{"+"\n"
			+"	background:#CCCCCC;"+"\n"
			+"}"+"\n"
			+"/* * */.pro_mesage_left_title{"+"\n"
			+"	background:url(https://timage.pushauction.com/v3/DefaultTemplate/A16285/category_bg.jpg);"+"\n"
			+"	line-height: 42px;"+"\n"
			+"	font-size:14px;"+"\n"
			+"	color:#ffffff;"+"\n"
			+"	font-weight: 600;"+"\n"
			+"	padding-left:15px;"+"\n"
			+"}"+"\n"
			+".store_category_nav_mes{"+"\n"
			+"	margin-left:10px;"+"\n"
			+"	line-height: 22px;"+"\n"
			+"}"+"\n"
			+".pro_mesage_left2{"+"\n"
			+"	width:220px;"+"\n"
			+"	height:136px;"+"\n"
			+"	background:#918d9b;"+"\n"
			+"	color: #ffffff;"+"\n"
			+"	text-align: center;"+"\n"
			+"	line-height:18px;"+"\n"
			+"	margin:15px 0;"+"\n"
			+"}"+"\n"
			+".pro_mesage_left2 p{"+"\n"
			+"	margin:8px 0;"+"\n"
			+"}"+"\n"
			+".also_like_nav_mes{"+"\n"
			+"	padding: 5px;;"+"\n"
			+"	margin:20px auto;"+"\n"
			+"	border:solid 1px #ffffff;"+"\n"
			+"	width:180px;"+"\n"
			+"	overflow: hidden;"+"\n"
			+"}"+"\n"
			+" /*增加 */.also_like_nav_mes img{"+"\n"
			+"	width:180px;	"+"\n"
			+"	height:200px;"+"\n"
			+"}"+"\n"
			+".also_like_nav_mes:hover{"+"\n"
			+"	border:solid 1px #918e9b;;"+"\n"
			+"}"+"\n"
			+".also_like_nav_mes p{"+"\n"
			+"	color:#000000;"+"\n"
			+"	font-size:12px;"+"\n"
			+"}"+"\n"
			+".also_like_mes{"+"\n"
			+"	margin-bottom:5px;	"+"\n"
			+"}"+"\n"
			+".also_like_mes:hover{"+"\n"
			+"	text-decoration: underline;"+"\n"
			+"}"+"\n"
			+".also_like_price{"+"\n"
			+"	line-height:20px;"+"\n"
			+"}"+"\n"
			+".pro_mesage_center{"+"\n"
			+"	width:602px;	"+"\n"
			+"}"+"\n"
			+".section_body{"+"\n"
			+"	width:866px;		"+"\n"
			+"	margin-left:13px;"+"\n"
			+"}"+"\n"
			+".pro_display,.pro_display2{"+"\n"
			+"	width:865px;"+"\n"
			+"	padding-bottom:10px;"+"\n"
			+"	margin-bottom:20px;"+"\n"
			+"	background:#ffffff;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".pro_display2{	"+"\n"
			+"	margin-bottom:15px;"+"\n"
			+"}"+"\n"
			+".introduce{"+"\n"
			+"	line-height:40px;"+"\n"
			+"	font-size:18px;"+"\n"
			+"	font-weight: 300;"+"\n"
			+"	color:#666666;"+"\n"
			+"	margin-left:130px;"+"\n"
			+"}"+"\n"
			+".sign{"+"\n"
			+"	width:181px;"+"\n"
			+"	height:26px;"+"\n"
			+"	background:#faede5;"+"\n"
			+"	color: #918d9b;"+"\n"
			+"	text-align: center;"+"\n"
			+"	line-height:26px;"+"\n"
			+"	margin:0px auto;"+"\n"
			+"	cursor:pointer;"+"\n"
			+"}"+"\n"
			+".produce_descri_title span{margin-left:20px;}"+"\n"
			+".produce_descri_title{"+"\n"
			+"	background:#faede5;"+"\n"
			+"	font-weight: 300;"+"\n"
			+"	line-height: 48px;"+"\n"
			+"	width:100%;"+"\n"
			+"	border-bottom:1px solid #ffffff;"+"\n"
			+"	font-weight: bold;"+"\n"
			+"	margin-bottom:2px;"+"\n"
			+"}"+"\n"
			+".produce_descri{"+"\n"
			+"	padding:20px;"+"\n"
			+"	background:#ffffff;"+"\n"
			+"	line-height: 24px;"+"\n"
			+"	word-wrap:break-word;"+"\n"
			+"}"+"\n"
			+".description{"+"\n"
			+"	margin-top:10px;"+"\n"
			+"	line-height:20px;"+"\n"
			+"}"+"\n"
			+".faq{width:inherit;}"+"\n"
			+"/*删除*/"+"\n"
			+".produce_descri_img{"+"\n"
			+"	width:798px;"+"\n"
			+"	margin:0 auto;"+"\n"
			+"}"+"\n"
			+"/*增加*/.paypal{"+"\n"
			+"	width:280px;"+"\n"
			+"	height: 56px;"+"\n"
			+"	background: url(https://image.pushauction.com/0/0/c51cbac2-a574-4c90-811c-c6ad65ff28b2/6827ff85-4722-4507-85b9-c66ae0cc7ac2.png);"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".produce_descri_word{"+"\n"
			+"	line-height: 52px;"+"\n"
			+"}"+"\n"
			+"table{"+"\n"
			+"	border:none;"+"\n"
			+"	margin-top:10px;"+"\n"
			+"}"+"\n"
			+"th,td{"+"\n"
			+"	padding-right: 100px;"+"\n"
			+"	line-height:30px;	"+"\n"
			+"}"+"\n"
			+".aboutus_descri,.Returns_descri{"+"\n"
			+"	line-height:20px;"+"\n"
			+"}"+"\n"
			+"/* * */.copy_right{"+"\n"
			+"	width:100%;"+"\n"
			+"	height:150px;"+"\n"
			+"	background:url(https://timage.pushauction.com/v3/DefaultTemplate/A16285/store_bottombg.jpg)"+"\n"
			+"}"+"\n"
			+".copy_right p{"+"\n"
			+"	color:#ffffff;"+"\n"
			+"	padding:10px 0 0 400px;"+"\n"
			+"	line-height:16px;"+"\n"
			+"	font-size:12px;"+"\n"
			+"}"+"\n"
			+".facebook_content{"+"\n"
			+"	margin:5px;"+"\n"
			+"	border-bottom:1px dashed #cccccc;"+"\n"
			+"}"+"\n"
			+".facebook{"+"\n"
			+"	margin-top:5px;"+"\n"
			+"	width:100%;"+"\n"
			+"}"+"\n"
			+".facebook_title{"+"\n"
			+"	padding-left:10px;"+"\n"
			+"	padding-right:10px;"+"\n"
			+"	background:#eeeeee;"+"\n"
			+"	border-top:1px solid #cccccc;"+"\n"
			+"	border-bottom:1px solid #cccccc;"+"\n"
			+"	line-height: 30px;;"+"\n"
			+"}"+"\n"
			+".facebook-left,.facebook-right {"+"\n"
			+"	line-height: 30px;"+"\n"
			+"	margin: 10px;"+"\n"
			+"}"+"\n"
			+".icon{"+"\n"
			+"	margin-top:4px;"+"\n"
			+"	margin-right:5px;"+"\n"
			+"	height:40px;"+"\n"
			+"}"+"\n"
			+".grey_line{"+"\n"
			+"	width:100%;"+"\n"
			+"	height:30px;"+"\n"
			+"	margin:30px 0 30px 0;"+"\n"
			+"	background:darkgray;"+"\n"
			+"}"+"\n"
			+"/* * */footer{"+"\n"
			+"	width:100%;"+"\n"
			+"	height:100%;"+"\n"
			+"	/*border-top:1px solid #A9A9A9;*/"+"\n"
			+"}"+"\n"
			+".powered{"+"\n"
			+"	width:104px;"+"\n"
			+"	margin:10px auto;"+"\n"
			+"}"+"\n"
			+".DataCaciques{"+"\n"
			+"	width:189px;"+"\n"
			+"	margin:0 auto; "+"\n"
			+"}"+"\n"
			+".article_footer ul{margin-left:7px;padding-bottom:5px;}"+"\n"
			+"#store_category_content{"+"\n"
			+"	width:865px;"+"\n"
			+"	height:600px;"+"\n"
			+"	position:relative;	"+"\n"
			+"}"+"\n"
			+".container_tab #c1,.container_tab #c2,.container_tab #c3,"+"\n"
			+".container_tab #c4,.container_tab #c5,.container_tab #c6,"+"\n"
			+".container_tab #c7,.container_tab #c8,.container_tab #c9{"+"\n"
			+"	position:absolute;"+"\n"
			+"	top:-200px;"+"\n"
			+"	padding-top:200px;"+"\n"
			+"}"+"\n"
			+"/*增加*/.tab-content img{width:600px;height:600px;}"+"\n"
			+"/*增加*/.container_tab > div > a > img{width:88px;height:88px;}"+"\n"
			+"/*增加*/.produce_descri_img > img{width:260px;height:173px;}"+"\n"
			+".container_tab div>.tab-content{"+"\n"
			+"	position:absolute !important;"+"\n"
			+"	padding-top:156px;"+"\n"
			+"	top:42px;"+"\n"
			+"	left:30px;"+"\n"
			+"}"+"\n"
			+".container_tab>div:target>.tab-content{"+"\n"
			+"	z-index:100;"+"\n"
			+"}"+"\n"
			+".container_tab> div>a{"+"\n"
			+"	display:inline-block;"+"\n"
			+"	position:absolute;"+"\n"
			+"	left:662px;"+"\n"
			+"	margin-left:5px;	"+"\n"
			+"} "+"\n"
			+"/* * */"+"\n"
			+"#c1{z-index: 10;}"+"\n"
			+"#c2 a{left:762px;top:200px;z-index: 9}"+"\n"
			+"#c4 a{left:762px;top:300px;z-index: 8}"+"\n"
			+"#c6 a{left:762px;top:400px;z-index: 7}"+"\n"
			+"#c8 a{left:762px;top:500px;z-index: 6}"+"\n"
			+"#c3 a{left:662px;top:300px;z-index: 5}"+"\n"
			+"#c5 a{left:662px;top:400px;z-index: 4}"+"\n"
			+"#c7 a{left:662px;top:500px;z-index: 3}"+"\n"
			+"#c9 a{left:662px;top:600px;z-index: 2}"+"\n"
			+".mask2{"+"\n"
			+"	width:88px;"+"\n"
			+"	height:88px;"+"\n"
			+"	background:#ffffff;"+"\n"
			+"	opacity: 0.8;"+"\n"
			+"	z-index: 100;"+"\n"
			+"	position:absolute;"+"\n"
			+"	top:0;"+"\n"
			+"	left:0;"+"\n"
			+"}"+"\n"
			+".container_tab>div:target>a>.mask2{opacity: 0;	}"+"\n"
			+".container_tab>div:target>a>img{border:1px solid black;}"+"\n"
			+"#blank{height:674px;}"+"\n"
			+"#body-body{width:107%;"+"\n"
			+ "}"+"\n";
 
	@Override
	public String getCss() {
		// TODO Auto-generated method stub
		return this.css;
	}


	public void setCss(String css){
		
		this.css=css;
	}


	
	
	
}
