package com.it.ocs.itemDescribe.css;

import com.it.ocs.itemDescribe.Base.BaseCss;

public class TemplateBCss extends BaseCss {
	
	public static String css = ".LE p,.LE ul{margin:0;padding:0;}"+"\n"
			+ ".LE{" +"\n"
		    + "font-family:arial;"+"\n"
		    + "}"+"\n"
		    + ".LE li{"+"\n"
		    + "list-style: none;"+"\n"
		    + "}"+"\n"
		    + "img{border:none;}"+"\n"
		    + ".LE a{text-decoration: none;cursor:pointer;}"+"\n"
		    + ".LE{"+"\n"
		    + "min-width:1400px;"+"\n"
		    + "}"+"\n"
		    + ".left{"+"\n"
		    + "float:left;"+"\n"
		    + "}"+"\n"
		    + ".right{"+"\n"
		    + "float:right;"+"\n"
		    + "}"+"\n"
		    + ".after:after{"+"\n"
		    + "content:\"\";"+"\n"
		    + "display: block;"+"\n"
		    + "clear: both;"+"\n"
		    + "}"+"\n"
		    + "#header-title{"+"\n"
		    + "min-width:1400px;"+"\n"
		    + "width: 100%;"+"\n"
		    + "height:200px;"+"\n"
		    + "background:-moz-linear-gradient(top,#fbfbfb,#b1d6b1,#6ab753);"+"\n"
		    + "background:-webkit-linear-gradient(top,#fbfbfb,#b1d6b1,#6ab753);"+"\n"
		    + "background:-ms-linear-gradient(top,#fbfbfb,#b1d6b1,#6ab753);"+"\n"
		    + "position:relative;"+"\n"
		    + "}"+"\n"
		    + ".main-logo{"+"\n"
		    + "margin:10px;"+"\n"
		    + "width: 122px;"+"\n"
		    + "height: 37px;"+"\n"
		    + "}"+"\n"
		    + ".contry{"+"\n"
		    + "position: absolute;"+"\n"
		    + "top: 24px;"+"\n"
		    + "right:120px;"+"\n"
		    + "}"+"\n"
		    + ".contry li{margin-left:30px;}"+"\n"
		    + "#Search{"+"\n"
		    + "width:320px;"+"\n"
		    + "height:32px;"+"\n"
		    + "position: absolute;"+"\n"
		    + "top: 56px;"+"\n"
		    + "right:120px;"+"\n"
		    + "padding:5px;"+"\n"
		    + "background-color:#fff;"+"\n"
		    + "/*background:url(../img/search.png) no-repeat;*/"+"\n"
		    + "/*background-position: 283px 13px;*/"+"\n"
		    + "}"+"\n"
		    + ".search-icon{"+"\n"
		    + "position:absolute;"+"\n"
		    + "top: 65px;"+"\n"
		    + "right:137px;"+"\n"
		    + "}"+"\n"
		    + ".main-title{"+"\n"
		    + "position: absolute;"+"\n"
		    + "top: -23px;"+"\n"
		    + "left:20%;"+"\n"
		    + "line-height:200px;"+"\n"
		    + "font-size:46px;"+"\n"
		    + "font-family:\"arial rounded mt bold\""+"\n"
		    + "}"+"\n"
		    + ".banner{"+"\n"
		    + "width:100%;"+"\n"
		    + "height:400px;"+"\n"
		    + "background: #f0fff0;"+"\n"
		    + "text-align: center;"+"\n"
		    + "color:darkgreen;"+"\n"
		    + "font-size:28px;"+"\n"
		    + "line-height: 400px;"+"\n"
		    + "}"+"\n"
		    + ".banner a{color:darkgreen;}"+"\n"
		    + "/*引进*/"+"\n"
		    + "#header .pro-display, .footer .pro-display{margin-top:10px;min-width:1400px;}"+"\n"
		    + ".pro-display li ,.aside-display li{"+"\n"
		    + "padding:0.5%;"+"\n"
		    + "font-size:12px;"+"\n"
		    + "display: inline-block;"+"\n"
		    + "border:1px solid #eee;"+"\n"
		    + "width:14.7%;"+"\n"
		    + "margin-right:0.57%;"+"\n"
		    + "}"+"\n"
		    + ".pro-display li:hover{"+"\n"
		    + "border:1px solid #008500;"+"\n"
		    + "}"+"\n"
		    + ".aside-display li:hover{"+"\n"
		    + "border:1px solid #008500;"+"\n"
		    + "}"+"\n"
		    + ".pro-display li:nth-of-type(6){"+"\n"
		    + "margin-right:0;"+"\n"
		    + "}"+"\n"
		    + ".product-box{position:relative;width:100%;}"+"\n"
		    + ".product-box p{height:68px;overflow:hidden;}"+"\n"
		    + ".aside-display li:after{"+"\n"
		    + "content:\"\";"+"\n"
		    + "display: block;"+"\n"
		    + "clear:both;"+"\n"
		    + "}"+"\n"
		    + ".product-show{width:100%;}"+"\n"
		    + ".discount-tap{"+"\n"
		    + "width:26%;"+"\n"
		    + "position:absolute;"+"\n"
		    + "top:0px;"+"\n"
		    + "right:0px;"+"\n"
		    + "}"+"\n"
		    + ".time{font-size:16px;}"+"\n"
		    + ".time-icon{width:30px;height:30px;}"+"\n"
		    + ".time-icon,.time{float:right;}"+"\n"
		    + ".price{"+"\n"
		    + "font-size:16px;"+"\n"
		    + "color:#008000;"+"\n"
		    + "font-weight: bold;"+"\n"
		    + "}"+"\n"
		    + ".product-box .product-descript{margin:10px 0;}"+"\n"
		    + ".product-descript a{"+"\n"
		    + "color:#000000;"+"\n"
		    + "}"+"\n"
		    + ".product-descript a:hover{"+"\n"
		    + "text-decoration:underline;"+"\n"
		    + "}"+"\n"
		    + "/*引进结束*/"+"\n"
		    + ".aside{"+"\n"
		    + "font-size:14px;"+"\n"
		    + "width:18%;"+"\n"
		    + "margin-right:2%;"+"\n"
		    + "}"+"\n"
		    + ".section-body{"+"\n"
		    + "width:80%;"+"\n"
		    + "position:relative;"+"\n"
		    + "}"+"\n"
		    + ".all-product-title{"+"\n"
		    + "border:1px solid #ccc;"+"\n"
		    + "border-bottom:none;"+"\n"
		    + "background:#ccc;"+"\n"
		    + "padding:8px;"+"\n"
		    + "}"+"\n"
		    + ".section{margin:46px 0;}"+"\n"
		    + ".menu-icon{width:20px;height:20px;}"+"\n"
		    + ".aside .menu-list{"+"\n"
		    + "padding:5px 0px 30px 0px;"+"\n"
		    + "line-height:24px;"+"\n"
		    + "border:1px solid #eee;"+"\n"
		    + "margin-bottom:20px;"+"\n"
		    + "}"+"\n"
	        + ".menu-list li{"+"\n"
		    + "padding-left:35px;"+"\n"
		    + "padding-right:10px;"+"\n"
		    + "}"+"\n"
	        + ".menu-list li:hover{"+"\n"
		    + "background:#eee;"+"\n"
		    + "}"+"\n"
	        + ".menu-list  a{"+"\n"
		    + "line-height:36px;"+"\n"
		    + "color:#626262;"+"\n"
		    + "}"+"\n"
	        + ".aside-display li{"+"\n"
		    + "width:92%;"+"\n"
		    + "margin-bottom: 30px;"+"\n"
		    + "padding:3%;"+"\n"
		    + "}"+"\n"
	        + ".aside-display{overflow: hidden;}"+"\n"
	        + ".section-body-title{"+"\n"
		    + "text-align: center;"+"\n"
		    + "font-size:30px;"+"\n"
		    + "font-weight: bold;"+"\n"
		    + "}"+"\n"
	        + ".section-body-tip{"+"\n"
		    + "text-align: center;"+"\n"
		    + "font-size:16px;"+"\n"
		    + "}"+"\n"
	        + ".tab-content{"+"\n"
		    + "width:70%;"+"\n"
		    + "/*border:1px solid #ccc;*/"+"\n"
		    + "position: relative;"+"\n"
			+ "top:0;"+"\n"
			+ "left:0;"+"\n"
			+ "}"+"\n"
			+ ".container_tab {height:1400px;width:100%;position:relative;top:15px;left:0;}"+"\n"
			+ "@media screen and (min-width: 500px) and (max-width: 1119px){"+"\n"
			+ "	.container_tab {height:878px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 1120px) and (max-width: 1400px){"+"\n"
			+ ".container_tab {height:886px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 1401px) and (max-width: 1550px){"+"\n"
			+ ".container_tab {height:914px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 1551px) and (max-width: 1650px){"+"\n"
			+ ".container_tab {height:980px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 1651px) and (max-width: 1700px){"+"\n"
			+ ".container_tab {height:1030px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 1701px) and (max-width: 1780px){"+"\n"
			+ ".container_tab {height:1050px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 1781px) and (max-width: 1850px){"+"\n"
			+ ".container_tab {height:1100px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 1851px) and (max-width: 1950px){"+"\n"
			+ ".container_tab {height:1150px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 1951px) and (max-width: 2050px){"+"\n"
			+ ".container_tab {height:1200px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 2051px) and (max-width: 2130px){"+"\n"
			+ ".container_tab {height:1250px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 2131px) and (max-width: 2230px){"+"\n"
			+ ".container_tab {height:1300px;}"+"\n"
			+ "}"+"\n"
			+ "@media screen and (min-width: 2231px) and (max-width: 2331px){"+"\n"
			+ ".container_tab {height:1350px;}"+"\n"
			+ "}"+"\n"
			+ ".tab-content img{width:100%;}"+"\n"
			+ "/*.tab-content{width:100%;}*/"+"\n"
			+ ".position{"+"\n"
			+ "	position:absolute;"+"\n"
			+ "	top:35px;"+"\n"
			+ "	left:0px;"+"\n"
			+ "	width:100%;"+"\n"
			+ "}"+"\n"
			+ ".preView{"+"\n"
			+ "width:10%;"+"\n"
			+ "height:10%;"+"\n"
			+ "position:absolute;"+"\n"
			+ "}"+"\n"
			+ ".mask2{"+"\n"
			+ "width:100%;"+"\n"
			+ "height:100%;"+"\n"
			+ "background:#ffffff;"+"\n"
			+ "opacity: 0.8;"+"\n"
			+ "z-index: 100;"+"\n"
			+ "position:absolute;"+"\n"
			+ "top:0;"+"\n"
			+ "left:0;"+"\n"
			+ "transition: 0.5s;"+"\n"
			+ "}"+"\n"
			+ ".preView img{"+"\n"
			+ "width:100%;"+"\n"
			+ "height:100%;"+"\n"
			+ "}"+"\n"
			+ ".preView-1,.preView-3,.preView-5,.preView-7,.preView-9,.preView-11{"+"\n"
			+ "	right:12%;"+"\n"
			+ "}"+"\n"
			+ ".preView-2,.preView-4,.preView-6,.preView-8,.preView-10,.preView-12{"+"\n"
			+ "right:0;"+"\n"
			+ "}"+"\n"
			+ ".preView-1,.preView-2{"+"\n"
			+ "	top:0;"+"\n"
			+ "}"+"\n"
			+ ".preView-3,.preView-4{"+"\n"
			+ "top:12%;"+"\n"
			+ "}"+"\n"
			+ ".preView-5,.preView-6{"+"\n"
			+ "top:24%;"+"\n"
			+ "}"+"\n"
			+ ".preView-7,.preView-8{"+"\n"
			+ "	top:36%;"+"\n"
			+ "}"+"\n"
			+ ".preView-9,.preView-10{"+"\n"
			+ "	top:48%;"+"\n"
			+ "}"+"\n"
			+ ".preView-11,.preView-12{"+"\n"
			+ "	top:60%;"+"\n"
			+ "}"+"\n"
			+ ".content-title{"+"\n"
			+ "	background: #b8f1c8;"+"\n"
			+ "	padding:15px;"+"\n"
			+ "}"+"\n"
			+ ".section-content p{word-wrap: break-word;}"+"\n"
			+ ".detial{"+"\n"
			+ "	position: relative;"+"\n"
			+ "	background: #fff;"+"\n"
			+ "	padding:30px 300px 30px 15px;"+"\n"
			+ "	border:1px solid  #b8f1c8;"+"\n"
			+ "	min-height:126px;"+"\n"
			+ "}"+"\n"
			+ ".content-wrap{margin-bottom:20px;}"+"\n"
			+ "table{"+"\n"
			+ "	border:none;"+"\n"
			+ "	margin-top:10px;"+"\n"
			+ "}"+"\n"
			+ "th,td{"+"\n"
			+ "	padding-right: 100px;"+"\n"
			+ "	line-height:30px;	"+"\n"
			+ "}"+"\n"
			+ ".container_tab>div:target>.tab-content{"+"\n"
			+ "	z-index:100px;"+"\n"
			+ "}"+"\n"
			+ ".container_tab>div:target>a>.mask2{opacity: 0;	}"+"\n"
			+ ".container_tab>div>a>img{"+"\n"
			+ "	border:border:1px solid white;"+"\n"
			+ "	transition: 1s;"+"\n"
			+ "}"+"\n"
			+ ".section-content-icon img{"+"\n"
			+ "	vertical-align: bottom;"+"\n"
			+ "	margin-right:20px;"+"\n"
			+ "}"+"\n"
			+ ".section-content-title{"+"\n"
			+ "	line-height: 32px;"+"\n"
			+ "}"+"\n"
			+ ".detial p,.detial img,.detial table{z-index:2;}"+"\n"
			+ ".return{"+"\n"
			+ "	background:url(../img/shopping-back.png) no-repeat;"+"\n"
			+ "	background-position: 92% 63%;"+"\n"
			+ "}"+"\n"
			+ ".shipment{"+"\n"
			+ "	background: url(../img/shipment-back.png) no-repeat ;"+"\n"
			+ "	background-position: 92% 63%;"+"\n"
			+ "}"+"\n"
			+ ".payment{"+"\n"
			+ "	background: url(../img/payment-back.png) no-repeat;"+"\n"
			+ "	background-position: 92% 63%;"+"\n"
			+ "}"+"\n"
			+ ".FAQ{"+"\n"
			+ "	background: url(../img/faq-back.png) no-repeat;"+"\n"
			+ "	background-position: 92% 63%;"+"\n"
			+ "}"+"\n"
			+ ".about-us{"+"\n"
			+ "	background: url(../img/about-back.png) no-repeat;"+"\n"
			+ "	background-position: 92% 63%;"+"\n"
			+ "}"+"\n"
			+ ".singUp{"+"\n"
			+ "	background:#008500;"+"\n"
			+ "	width:98%;"+"\n"
			+ "	padding:3% 1%;"+"\n"
			+ "	color:#fff;"+"\n"
			+ "	text-align: center;"+"\n"
			+ "	margin-bottom:20px;"+"\n"
			+ "}"+"\n"

			+ ".singBtn{"+"\n"
			+ "	border-radius: 10px;"+"\n"
			+ "	background: #fff;"+"\n"
			+ "	width:70%;"+"\n"
			+ "	margin:20px 15%;"+"\n"
			+ "	line-height:32px;"+"\n"
			+ "	color:#008500;"+"\n"
			+ "	cursor:pointer;"+"\n"
			+ "}"+"\n";

	@Override
	public String getCss() {
		// TODO Auto-generated method stub
		return css;
	}

}
